name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-
    - uses: ./.github/composite/setup
      with:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
    - name: Build the project (no tests, no lint etc)
      run: ./gradlew assemble
    - name: Upload the APK
      uses: actions/upload-artifact@v4
      with:
        name: evently-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/composite/setup
      with:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
    - name: Lint with Gradle
      run: ./gradlew lint

  spotless:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/composite/setup
      with:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
    - name: Spotless with Gradle
      run: ./gradlew spotlessCheck

  unit-tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/composite/setup
      with:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
    - name: Test with Gradle
      run: ./gradlew test

